---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    thoth-station.ninja/template-version: 0.2.0-dev
  labels:
    app: qeb-hwt
    component: webhook-recevier
  name: qeb-hwt-webhook-recevier
spec:
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    app: qeb-hwt
    component: webhook-recevier
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: qeb-hwt
        component: webhook-recevier
    spec:
      containers:
        - name: webhook-recevier
          env:
            - name: ENV
              value: dev
            - name: PYTHONPATH
              value: .
            - name: THOTH_DEPLOYMENT_NAME
              value: aicoe-psi-prod
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: sentry-dsn
                  name: qeb-hwt
          envFrom:
            - prefix: GITHUB_
              secretRef:
                name: qeb-hwt-github-app
          image: qeb-hwt-webhook-recevier:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 100m
        - name: ultrahook
          envFrom:
            - configMapRef:
                name: ultrahook
          image: ultrahook:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
            requests:
              cpu: 100m
      restartPolicy: Always
  test: false
